name: HTTP Request Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *" 
jobs:
  make-http-request:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # installd the python version needed

      - name: install python packages
        run: pip install requests

      - name: Run HTTP request script
        run: python script.py
